=== evercheck/AutomationTesting/Selen.Spec.Training/XCartTesting/Common/PageSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Page",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "controls": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "controlName": {
            "description": "The unique identifier for a page item, ex. username textbox",
            "type": "string"
          },
          "controlType": {
            "description": "Control type, ex. textbox",
            "enum": [ "Textbox", "Button", "BaseControl", "Hyperlink", "Table", "Combobox","Span" ]
          },
          "by": {
            "description": "by type of a page item",
            "enum": [ "ClassName", "CssSelector","Id","Name","LinkText","XPath","TagName","PartialLinkText" ]
          },
          "value": {
            "description": "value of by",
            "type": "string"
          }
        },
        "required": [
          "controlName",
          "by",
          "value",
          "controlType"
        ]
      }
    },
    "pageName": {
      "description": "The unique identifier for a page",
      "type": "string"
    },
    "title": {
      "description": "Title of the page",
      "type": "string"
    },
    "url": {
      "description": "Url of the page",
      "type": "string"
    }
  },
  "required": [ "pageName" ]
}

=== evercheck/AutomationTesting/Selen.Spec.Training/XCartTesting/Interfaces/CommonPage.json
{
  "$schema": "D:\\Programming\\GitHub\\AutomationTesting\\Selen.Spec.Training\\XCartTesting\\Interfaces\\PageSchema.json",
  "controls": [
    {
      "controlName": "Close Dialog",
      "controlType": "Button",
      "by": "CssSelector",
      "value": "button.ui-dialog-titlebar-close"
    }
  ],
  "pageName": "Common Page",
  "title": "",
  "url": ""
}

=== evercheck/AutomationTesting/Selen.Spec.Training/XCartTesting/Admin/Interfaces/AdminLoginPage.json
{
  "$schema": "../Common/PageSchema.json",
  "controls": [
    {
      "controlName": "Email",
      "controlType": "Textbox",
      "by": "Name",
      "value": "login"
    },
    {
      "controlName": "Password",
      "controlType": "Textbox",
      "by": "Name",
      "value": "password"
    },
    {
      "controlName": "Submit",
      "controlType": "Button",
      "by": "XPath",
      "value": "//*[@id='login_form']//button"
    }
  ],
  "pageName": "Admin Login Page",
  "title": "",
  "url": ""
}
